create table categories
(
    post_id  integer not null
        constraint fk_post
            references posts,
    category varchar not null
);

alter table categories
    owner to postgres;

INSERT INTO public.categories (post_id, category) VALUES (0, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (0, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (0, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (1, 'Skiing');
INSERT INTO public.categories (post_id, category) VALUES (1, 'Winter Sports');
INSERT INTO public.categories (post_id, category) VALUES (2, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (2, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (3, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (3, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (4, 'Hobby');
INSERT INTO public.categories (post_id, category) VALUES (5, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (5, 'Sleep');
INSERT INTO public.categories (post_id, category) VALUES (6, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (6, 'Education');
INSERT INTO public.categories (post_id, category) VALUES (7, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (7, 'Recipe');
INSERT INTO public.categories (post_id, category) VALUES (8, 'Meditation');
INSERT INTO public.categories (post_id, category) VALUES (8, 'Mindfulness');
INSERT INTO public.categories (post_id, category) VALUES (9, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (9, 'Spanish');
INSERT INTO public.categories (post_id, category) VALUES (10, 'Sport');
INSERT INTO public.categories (post_id, category) VALUES (10, 'Tennis');
INSERT INTO public.categories (post_id, category) VALUES (11, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (11, 'Album');
INSERT INTO public.categories (post_id, category) VALUES (11, 'New Release');
INSERT INTO public.categories (post_id, category) VALUES (12, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (12, 'Favorites');
INSERT INTO public.categories (post_id, category) VALUES (13, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (13, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (14, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (14, 'Outdoors');
INSERT INTO public.categories (post_id, category) VALUES (15, 'Basketball');
INSERT INTO public.categories (post_id, category) VALUES (15, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (16, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (16, 'Guitar');
INSERT INTO public.categories (post_id, category) VALUES (17, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (17, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (17, 'Healthy Living');
INSERT INTO public.categories (post_id, category) VALUES (18, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (18, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (19, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (19, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (20, 'Language');
INSERT INTO public.categories (post_id, category) VALUES (20, 'Culture');
INSERT INTO public.categories (post_id, category) VALUES (20, 'Learning');
INSERT INTO public.categories (post_id, category) VALUES (21, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (21, 'Personal Growth');
INSERT INTO public.categories (post_id, category) VALUES (22, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (22, 'Spanish');
INSERT INTO public.categories (post_id, category) VALUES (23, 'Art');
INSERT INTO public.categories (post_id, category) VALUES (23, 'Painting');
INSERT INTO public.categories (post_id, category) VALUES (23, 'Hobby');
INSERT INTO public.categories (post_id, category) VALUES (24, 'Yoga');
INSERT INTO public.categories (post_id, category) VALUES (24, 'Stress Relief');
INSERT INTO public.categories (post_id, category) VALUES (25, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (25, 'Challenges');
INSERT INTO public.categories (post_id, category) VALUES (26, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (26, 'Solo Travel');
INSERT INTO public.categories (post_id, category) VALUES (27, 'Memory');
INSERT INTO public.categories (post_id, category) VALUES (27, 'Brain');
INSERT INTO public.categories (post_id, category) VALUES (28, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (28, 'Sushi');
INSERT INTO public.categories (post_id, category) VALUES (29, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (29, 'Spanish');
INSERT INTO public.categories (post_id, category) VALUES (30, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (30, 'Learning');
INSERT INTO public.categories (post_id, category) VALUES (31, 'Skiing');
INSERT INTO public.categories (post_id, category) VALUES (31, 'Winter Sports');
INSERT INTO public.categories (post_id, category) VALUES (32, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (32, 'Personal Development');
INSERT INTO public.categories (post_id, category) VALUES (33, 'Learning');
INSERT INTO public.categories (post_id, category) VALUES (33, 'Personal Growth');
INSERT INTO public.categories (post_id, category) VALUES (34, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (34, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (35, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (35, 'Career');
INSERT INTO public.categories (post_id, category) VALUES (36, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (36, 'Tips');
INSERT INTO public.categories (post_id, category) VALUES (37, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (37, 'Tips');
INSERT INTO public.categories (post_id, category) VALUES (38, 'Skydiving');
INSERT INTO public.categories (post_id, category) VALUES (38, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (39, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (39, 'Paris');
INSERT INTO public.categories (post_id, category) VALUES (40, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (40, 'Recipe');
INSERT INTO public.categories (post_id, category) VALUES (40, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (41, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (41, 'Thrill-Seeking');
INSERT INTO public.categories (post_id, category) VALUES (42, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (42, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (43, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (43, 'Rock');
INSERT INTO public.categories (post_id, category) VALUES (44, 'Skydiving');
INSERT INTO public.categories (post_id, category) VALUES (44, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (44, 'Fear');
INSERT INTO public.categories (post_id, category) VALUES (45, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (45, 'Guitar');
INSERT INTO public.categories (post_id, category) VALUES (46, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (46, 'French');
INSERT INTO public.categories (post_id, category) VALUES (47, 'Sushi');
INSERT INTO public.categories (post_id, category) VALUES (47, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (48, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (48, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (49, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (49, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (50, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (50, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (51, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (51, 'Healthy Lifestyle');
INSERT INTO public.categories (post_id, category) VALUES (52, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (52, 'Spanish');
INSERT INTO public.categories (post_id, category) VALUES (53, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (53, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (54, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (54, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (55, 'Meditation');
INSERT INTO public.categories (post_id, category) VALUES (55, 'Mindfulness');
INSERT INTO public.categories (post_id, category) VALUES (56, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (56, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (57, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (57, 'Piano');
INSERT INTO public.categories (post_id, category) VALUES (58, 'Reading');
INSERT INTO public.categories (post_id, category) VALUES (58, 'Self-Improvement');
INSERT INTO public.categories (post_id, category) VALUES (59, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (59, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (60, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (60, 'Benefits');
INSERT INTO public.categories (post_id, category) VALUES (61, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (61, 'Outdoors');
INSERT INTO public.categories (post_id, category) VALUES (62, 'Yoga');
INSERT INTO public.categories (post_id, category) VALUES (62, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (63, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (63, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (64, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (64, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (65, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (65, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (66, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (66, 'Self-discovery');
INSERT INTO public.categories (post_id, category) VALUES (67, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (67, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (68, 'Piano');
INSERT INTO public.categories (post_id, category) VALUES (68, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (68, 'Learning');
INSERT INTO public.categories (post_id, category) VALUES (69, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (69, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (69, 'Mountains');
INSERT INTO public.categories (post_id, category) VALUES (70, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (70, 'Self-improvement');
INSERT INTO public.categories (post_id, category) VALUES (71, 'Meditation');
INSERT INTO public.categories (post_id, category) VALUES (71, 'Mental Health');
INSERT INTO public.categories (post_id, category) VALUES (72, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (72, 'Outdoors');
INSERT INTO public.categories (post_id, category) VALUES (73, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (73, 'Healthy Lifestyle');
INSERT INTO public.categories (post_id, category) VALUES (74, 'Bungee Jumping');
INSERT INTO public.categories (post_id, category) VALUES (74, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (75, 'Photography');
INSERT INTO public.categories (post_id, category) VALUES (75, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (76, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (76, 'Rock Climbing');
INSERT INTO public.categories (post_id, category) VALUES (77, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (78, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (78, 'Spanish');
INSERT INTO public.categories (post_id, category) VALUES (79, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (79, 'French');
INSERT INTO public.categories (post_id, category) VALUES (80, 'Skydiving');
INSERT INTO public.categories (post_id, category) VALUES (80, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (81, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (81, 'Spanish');
INSERT INTO public.categories (post_id, category) VALUES (82, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (82, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (83, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (84, 'Skiing');
INSERT INTO public.categories (post_id, category) VALUES (84, 'Winter Sports');
INSERT INTO public.categories (post_id, category) VALUES (85, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (85, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (86, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (86, 'Quarantine');
INSERT INTO public.categories (post_id, category) VALUES (87, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (87, 'Solo Travel');
INSERT INTO public.categories (post_id, category) VALUES (88, 'Surfing');
INSERT INTO public.categories (post_id, category) VALUES (88, 'Beach');
INSERT INTO public.categories (post_id, category) VALUES (89, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (89, 'Solo Travel');
INSERT INTO public.categories (post_id, category) VALUES (90, 'Skydiving');
INSERT INTO public.categories (post_id, category) VALUES (90, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (91, 'Meditation');
INSERT INTO public.categories (post_id, category) VALUES (91, 'Mindfulness');
INSERT INTO public.categories (post_id, category) VALUES (92, 'Meditation');
INSERT INTO public.categories (post_id, category) VALUES (92, 'Mindfulness');
INSERT INTO public.categories (post_id, category) VALUES (93, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (93, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (94, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (94, 'Favorite');
INSERT INTO public.categories (post_id, category) VALUES (95, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (95, 'Recipes');
INSERT INTO public.categories (post_id, category) VALUES (95, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (96, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (96, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (96, 'Healthy Lifestyle');
INSERT INTO public.categories (post_id, category) VALUES (97, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (97, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (98, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (98, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (99, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (99, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (100, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (100, 'Festival');
INSERT INTO public.categories (post_id, category) VALUES (101, 'yoga');
INSERT INTO public.categories (post_id, category) VALUES (101, 'health');
INSERT INTO public.categories (post_id, category) VALUES (101, 'mindfulness');
INSERT INTO public.categories (post_id, category) VALUES (102, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (102, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (102, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (103, 'Rock Climbing');
INSERT INTO public.categories (post_id, category) VALUES (103, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (104, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (104, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (104, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (105, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (105, 'Pizza');
INSERT INTO public.categories (post_id, category) VALUES (106, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (106, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (107, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (107, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (108, 'Skiing');
INSERT INTO public.categories (post_id, category) VALUES (108, 'Winter Sports');
INSERT INTO public.categories (post_id, category) VALUES (109, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (109, 'Nutrition');
INSERT INTO public.categories (post_id, category) VALUES (110, 'Productivity');
INSERT INTO public.categories (post_id, category) VALUES (110, 'Time Management');
INSERT INTO public.categories (post_id, category) VALUES (110, 'Goal Setting');
INSERT INTO public.categories (post_id, category) VALUES (111, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (111, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (112, 'Language');
INSERT INTO public.categories (post_id, category) VALUES (112, 'Education');
INSERT INTO public.categories (post_id, category) VALUES (113, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (113, 'Tennis');
INSERT INTO public.categories (post_id, category) VALUES (114, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (114, 'Japan');
INSERT INTO public.categories (post_id, category) VALUES (115, 'outdoors');
INSERT INTO public.categories (post_id, category) VALUES (115, 'hiking');
INSERT INTO public.categories (post_id, category) VALUES (115, 'camping');
INSERT INTO public.categories (post_id, category) VALUES (115, 'fishing');
INSERT INTO public.categories (post_id, category) VALUES (116, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (116, 'Vegetarianism');
INSERT INTO public.categories (post_id, category) VALUES (117, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (117, 'Tips');
INSERT INTO public.categories (post_id, category) VALUES (118, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (118, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (118, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (119, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (119, 'Favorite Genre');
INSERT INTO public.categories (post_id, category) VALUES (120, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (120, 'Rock');
INSERT INTO public.categories (post_id, category) VALUES (121, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (121, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (122, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (122, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (123, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (123, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (124, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (124, 'Europe');
INSERT INTO public.categories (post_id, category) VALUES (125, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (125, 'Tips');
INSERT INTO public.categories (post_id, category) VALUES (126, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (126, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (127, 'Rock Climbing');
INSERT INTO public.categories (post_id, category) VALUES (127, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (128, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (128, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (129, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (129, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (130, 'Meditation');
INSERT INTO public.categories (post_id, category) VALUES (130, 'Mindfulness');
INSERT INTO public.categories (post_id, category) VALUES (131, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (131, 'Jazz');
INSERT INTO public.categories (post_id, category) VALUES (131, 'Blues');
INSERT INTO public.categories (post_id, category) VALUES (132, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (132, 'Beach');
INSERT INTO public.categories (post_id, category) VALUES (133, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (133, 'Piano');
INSERT INTO public.categories (post_id, category) VALUES (134, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (134, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (135, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (135, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (136, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (136, 'Concert');
INSERT INTO public.categories (post_id, category) VALUES (137, 'Scuba Diving');
INSERT INTO public.categories (post_id, category) VALUES (137, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (138, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (138, 'French');
INSERT INTO public.categories (post_id, category) VALUES (139, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (139, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (140, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (140, 'Personal Development');
INSERT INTO public.categories (post_id, category) VALUES (141, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (141, 'Spanish');
INSERT INTO public.categories (post_id, category) VALUES (142, 'Beach');
INSERT INTO public.categories (post_id, category) VALUES (142, 'Vacation');
INSERT INTO public.categories (post_id, category) VALUES (143, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (143, 'Spanish');
INSERT INTO public.categories (post_id, category) VALUES (144, 'Yoga');
INSERT INTO public.categories (post_id, category) VALUES (144, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (145, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (145, 'Basketball');
INSERT INTO public.categories (post_id, category) VALUES (146, 'Sport');
INSERT INTO public.categories (post_id, category) VALUES (146, 'Tennis');
INSERT INTO public.categories (post_id, category) VALUES (147, 'Yoga');
INSERT INTO public.categories (post_id, category) VALUES (147, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (148, 'Science');
INSERT INTO public.categories (post_id, category) VALUES (148, 'Education');
INSERT INTO public.categories (post_id, category) VALUES (149, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (149, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (150, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (150, 'Skydiving');
INSERT INTO public.categories (post_id, category) VALUES (150, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (151, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (151, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (152, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (152, 'Concert');
INSERT INTO public.categories (post_id, category) VALUES (153, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (153, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (153, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (154, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (154, 'Rock Climbing');
INSERT INTO public.categories (post_id, category) VALUES (155, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (155, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (155, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (156, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (156, 'French');
INSERT INTO public.categories (post_id, category) VALUES (157, 'Sport');
INSERT INTO public.categories (post_id, category) VALUES (157, 'Basketball');
INSERT INTO public.categories (post_id, category) VALUES (158, 'Reading');
INSERT INTO public.categories (post_id, category) VALUES (158, 'Habit');
INSERT INTO public.categories (post_id, category) VALUES (159, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (159, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (159, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (160, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (160, 'Beach');
INSERT INTO public.categories (post_id, category) VALUES (161, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (161, 'Personal Growth');
INSERT INTO public.categories (post_id, category) VALUES (162, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (162, 'Tennis');
INSERT INTO public.categories (post_id, category) VALUES (163, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (163, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (164, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (164, 'Pop');
INSERT INTO public.categories (post_id, category) VALUES (164, 'Rock');
INSERT INTO public.categories (post_id, category) VALUES (164, 'Jazz');
INSERT INTO public.categories (post_id, category) VALUES (165, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (165, 'Japan');
INSERT INTO public.categories (post_id, category) VALUES (166, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (166, 'Exercise');
INSERT INTO public.categories (post_id, category) VALUES (167, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (167, 'Piano');
INSERT INTO public.categories (post_id, category) VALUES (168, 'Meditation');
INSERT INTO public.categories (post_id, category) VALUES (168, 'Self-improvement');
INSERT INTO public.categories (post_id, category) VALUES (169, 'Surfing');
INSERT INTO public.categories (post_id, category) VALUES (169, 'Beach');
INSERT INTO public.categories (post_id, category) VALUES (169, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (170, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (170, 'French');
INSERT INTO public.categories (post_id, category) VALUES (171, 'Marathon');
INSERT INTO public.categories (post_id, category) VALUES (171, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (172, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (172, 'Japan');
INSERT INTO public.categories (post_id, category) VALUES (173, 'Reading');
INSERT INTO public.categories (post_id, category) VALUES (173, 'Books');
INSERT INTO public.categories (post_id, category) VALUES (174, 'Skiing');
INSERT INTO public.categories (post_id, category) VALUES (174, 'Winter Sports');
INSERT INTO public.categories (post_id, category) VALUES (175, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (175, 'Outdoors');
INSERT INTO public.categories (post_id, category) VALUES (176, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (176, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (177, 'health');
INSERT INTO public.categories (post_id, category) VALUES (177, 'tea');
INSERT INTO public.categories (post_id, category) VALUES (178, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (178, 'Outdoors');
INSERT INTO public.categories (post_id, category) VALUES (178, 'Personal Growth');
INSERT INTO public.categories (post_id, category) VALUES (179, 'Skiing');
INSERT INTO public.categories (post_id, category) VALUES (179, 'Winter Sports');
INSERT INTO public.categories (post_id, category) VALUES (180, 'Astronomy');
INSERT INTO public.categories (post_id, category) VALUES (180, 'Stargazing');
INSERT INTO public.categories (post_id, category) VALUES (181, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (181, 'Personal Growth');
INSERT INTO public.categories (post_id, category) VALUES (182, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (182, 'Culture');
INSERT INTO public.categories (post_id, category) VALUES (183, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (183, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (184, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (184, 'Fitness');
INSERT INTO public.categories (post_id, category) VALUES (184, 'Running');
INSERT INTO public.categories (post_id, category) VALUES (185, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (185, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (186, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (186, 'Culture');
INSERT INTO public.categories (post_id, category) VALUES (187, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (187, 'Basketball');
INSERT INTO public.categories (post_id, category) VALUES (188, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (188, 'Tokyo');
INSERT INTO public.categories (post_id, category) VALUES (189, 'Music');
INSERT INTO public.categories (post_id, category) VALUES (189, 'Favorite Genre');
INSERT INTO public.categories (post_id, category) VALUES (190, 'Yoga');
INSERT INTO public.categories (post_id, category) VALUES (190, 'Health');
INSERT INTO public.categories (post_id, category) VALUES (191, 'Sports');
INSERT INTO public.categories (post_id, category) VALUES (191, 'Football');
INSERT INTO public.categories (post_id, category) VALUES (192, 'Meditation');
INSERT INTO public.categories (post_id, category) VALUES (192, 'Self-Care');
INSERT INTO public.categories (post_id, category) VALUES (193, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (193, 'Food');
INSERT INTO public.categories (post_id, category) VALUES (194, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (194, 'Culture');
INSERT INTO public.categories (post_id, category) VALUES (195, 'Bungee Jumping');
INSERT INTO public.categories (post_id, category) VALUES (195, 'Adventure');
INSERT INTO public.categories (post_id, category) VALUES (196, 'Language Learning');
INSERT INTO public.categories (post_id, category) VALUES (196, 'Tips');
INSERT INTO public.categories (post_id, category) VALUES (197, 'Skiing');
INSERT INTO public.categories (post_id, category) VALUES (197, 'Winter Sports');
INSERT INTO public.categories (post_id, category) VALUES (198, 'Green Tea');
INSERT INTO public.categories (post_id, category) VALUES (198, 'Healthy Lifestyle');
INSERT INTO public.categories (post_id, category) VALUES (199, 'Cooking');
INSERT INTO public.categories (post_id, category) VALUES (199, 'Quarantine');
INSERT INTO public.categories (post_id, category) VALUES (200, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (200, 'Beach');
INSERT INTO public.categories (post_id, category) VALUES (201, 'Hiking');
INSERT INTO public.categories (post_id, category) VALUES (201, 'Nature');
INSERT INTO public.categories (post_id, category) VALUES (202, 'Travel');
INSERT INTO public.categories (post_id, category) VALUES (202, 'Japan');
